### ISSUE TITLE
Fuzzing scope  from private invite

### ISSUE THREAD

**Issue by gopinath6** [zricethezav/h1domains#1]
Is there any chance to scrap domains from private invites?

**Comment by zricethezav** [comment]
@gopinath6 I do not plan on implementing this feature. You could fork and try implementing it yourself. I would suspect you need to use a different api endpoint and access token

**Comment by gopinath6** [comment]
ok fine

**Comment by m3dsec** [comment]
check this one
https://github.com/m3dsec/h1getPrograms

**Comment by gopinath6** [comment]
@m3dsec  thanks
